### ISSUE TITLE
[meta] Migrate instruction selection to ISLE

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#3713]
This is a meta issue to track the migration from hand-written instruction selection and lowering over to using the ISLE DSL.

As you port lowering for a clif opcode over to ISLE, please check the associated box (or leave a comment, if you don't have edit permissions and I or someone else can check the box for you). Hopefully this will help us focus our porting efforts and finish the migration in a timely manner, as well as avoid stepping on each others toes by having two people accidentally port the same opcode lowerings.

cc @alexcrichton @cfallin @abrown @jlb6740 @uweigand @sparker-arm @akirilov-arm 

# x86_64

<details>

* [ ] `Opcode::Clz`
* [ ] `Opcode::Ctz`
* [ ] `Opcode::Popcnt`
* [ ] `Opcode::Bitrev`
* [ ] `Opcode::IsNull`
* [ ] `Opcode::IsInvalid`
* [ ] `Opcode::Uextend`
* [ ] `Opcode::Sextend`
* [ ] `Opcode::Breduce`
* [ ] `Opcode::Bextend`
* [ ] `Opcode::Ireduce`
* [ ] `Opcode::Bint`
* [ ] `Opcode::Icmp`
* [ ] `Opcode::Fcmp`
* [ ] `Opcode::FallthroughReturn`
* [ ] `Opcode::Return`
* [ ] `Opcode::Call`
* [ ] `Opcode::CallIndirect`
* [ ] `Opcode::Debugtrap`
* [ ] `Opcode::Trapif`
* [ ] `Opcode::Trapff`
* [ ] `Opcode::WideningPairwiseDotProductS`
* [ ] `Opcode::Fadd`
* [ ] `Opcode::Fsub`
* [ ] `Opcode::Fmul`
* [ ] `Opcode::Fdiv`
* [ ] `Opcode::Fmin`
* [ ] `Opcode::Fmax`
* [ ] `Opcode::FminPseudo`
* [ ] `Opcode::FmaxPseudo`
* [ ] `Opcode::Sqrt`
* [ ] `Opcode::Fpromote`
* [ ] `Opcode::FvpromoteLow`
* [ ] `Opcode::Fdemote`
* [ ] `Opcode::Fvdemote`
* [ ] `Opcode::FcvtFromSint`
* [ ] `Opcode::FcvtLowFromSint`
* [ ] `Opcode::FcvtFromUint`
* [ ] `Opcode::FcvtToUint`
* [ ] `Opcode::FcvtToUintSat`
* [ ] `Opcode::FcvtToSint`
* [ ] `Opcode::FcvtToSintSat`
* [ ] `Opcode::IaddPairwise`
* [ ] `Opcode::UwidenHigh`
* [ ] `Opcode::UwidenLow`
* [ ] `Opcode::SwidenHigh`
* [ ] `Opcode::SwidenLow`
* [ ] `Opcode::Snarrow`
* [ ] `Opcode::Unarrow`
* [ ] `Opcode::Bitcast`
* [ ] `Opcode::Fabs`
* [ ] `Opcode::Fneg`
* [ ] `Opcode::Fcopysign`
* [ ] `Opcode::Ceil`
* [ ] `Opcode::Floor`
* [ ] `Opcode::Nearest`
* [ ] `Opcode::Trunc`
* [ ] `Opcode::Load`
* [ ] `Opcode::Uload8`
* [ ] `Opcode::Sload8`
* [ ] `Opcode::Uload16`
* [ ] `Opcode::Sload16`
* [ ] `Opcode::Uload32`
* [ ] `Opcode::Sload32`
* [ ] `Opcode::LoadComplex`
* [ ] `Opcode::Uload8Complex`
* [ ] `Opcode::Sload8Complex`
* [ ] `Opcode::Uload16Complex`
* [ ] `Opcode::Sload16Complex`
* [ ] `Opcode::Uload32Complex`
* [ ] `Opcode::Sload32Complex`
* [ ] `Opcode::Sload8x8`
* [ ] `Opcode::Uload8x8`
* [ ] `Opcode::Sload16x4`
* [ ] `Opcode::Uload16x4`
* [ ] `Opcode::Sload32x2`
* [ ] `Opcode::Uload32x2`
* [ ] `Opcode::Store`
* [ ] `Opcode::Istore8`
* [ ] `Opcode::Istore16`
* [ ] `Opcode::Istore32`
* [ ] `Opcode::StoreComplex`
* [ ] `Opcode::Istore8Complex`
* [ ] `Opcode::Istore16Complex`
* [ ] `Opcode::Istore32Complex`
* [ ] `Opcode::AtomicRmw`
* [ ] `Opcode::AtomicCas`
* [ ] `Opcode::AtomicLoad`
* [ ] `Opcode::AtomicStore`
* [ ] `Opcode::Fence`
* [ ] `Opcode::FuncAddr`
* [ ] `Opcode::SymbolValue`
* [ ] `Opcode::StackAddr`
* [ ] `Opcode::Select`
* [ ] `Opcode::Selectif`
* [ ] `Opcode::SelectifSpectreGuard`
* [ ] `Opcode::Udiv`
* [ ] `Opcode::Urem`
* [ ] `Opcode::Sdiv`
* [ ] `Opcode::Srem`
* [ ] `Opcode::Umulhi`
* [ ] `Opcode::Smulhi`
* [ ] `Opcode::GetPinnedReg`
* [ ] `Opcode::SetPinnedReg`
* [ ] `Opcode::Vconst`
* [ ] `Opcode::RawBitcast`
* [ ] `Opcode::Shuffle`
* [ ] `Opcode::Swizzle`
* [ ] `Opcode::Insertlane`
* [ ] `Opcode::Extractlane`
* [ ] `Opcode::ScalarToVector`
* [ ] `Opcode::Splat`
* [ ] `Opcode::VanyTrue`
* [ ] `Opcode::VallTrue`
* [ ] `Opcode::VhighBits`
* [ ] `Opcode::Iconcat`
* [ ] `Opcode::Isplit`
* [ ] `Opcode::TlsValue`
* [ ] `Opcode::SqmulRoundSat`
* [ ] `Opcode::Uunarrow`

</details>

# aarch64

<details>

* [ ] `Opcode::Load`
* [ ] `Opcode::Uload8`
* [ ] `Opcode::Sload8`
* [ ] `Opcode::Uload16`
* [ ] `Opcode::Sload16`
* [ ] `Opcode::Uload32`
* [ ] `Opcode::Sload32`
* [ ] `Opcode::LoadComplex`
* [ ] `Opcode::Uload8Complex`
* [ ] `Opcode::Sload8Complex`
* [ ] `Opcode::Uload16Complex`
* [ ] `Opcode::Sload16Complex`
* [ ] `Opcode::Uload32Complex`
* [ ] `Opcode::Sload32Complex`
* [ ] `Opcode::Sload8x8`
* [ ] `Opcode::Uload8x8`
* [ ] `Opcode::Sload16x4`
* [ ] `Opcode::Uload16x4`
* [ ] `Opcode::Sload32x2`
* [ ] `Opcode::Uload32x2`
* [ ] `Opcode::Uload8x8Complex`
* [ ] `Opcode::Sload8x8Complex`
* [ ] `Opcode::Uload16x4Complex`
* [ ] `Opcode::Sload16x4Complex`
* [ ] `Opcode::Uload32x2Complex`
* [ ] `Opcode::Sload32x2Complex`
* [ ] `Opcode::Store`
* [ ] `Opcode::Istore8`
* [ ] `Opcode::Istore16`
* [ ] `Opcode::Istore32`
* [ ] `Opcode::StoreComplex`
* [ ] `Opcode::Istore8Complex`
* [ ] `Opcode::Istore16Complex`
* [ ] `Opcode::Istore32Complex`
* [ ] `Opcode::StackAddr`
* [ ] `Opcode::AtomicRmw`
* [ ] `Opcode::AtomicCas`
* [ ] `Opcode::AtomicLoad`
* [ ] `Opcode::AtomicStore`
* [ ] `Opcode::Fence`
* [ ] `Opcode::Select`
* [ ] `Opcode::Selectif`
* [ ] `Opcode::SelectifSpectreGuard`
* [ ] `Opcode::Bitselect`
* [ ] `Opcode::Vselect`
* [ ] `Opcode::Trueif`
* [ ] `Opcode::Trueff`
* [ ] `Opcode::IsNull`
* [ ] `Opcode::IsInvalid`
* [ ] `Opcode::Copy`
* [ ] `Opcode::Breduce`
* [ ] `Opcode::Ireduce`
* [ ] `Opcode::Bextend`
* [ ] `Opcode::Bmask`
* [ ] `Opcode::Bint`
* [ ] `Opcode::Bitcast`
* [ ] `Opcode::FallthroughReturn`
* [ ] `Opcode::Return`
* [ ] `Opcode::Icmp`
* [ ] `Opcode::Fcmp`
* [ ] `Opcode::Debugtrap`
* [ ] `Opcode::Trap`
* [ ] `Opcode::ResumableTrap`
* [ ] `Opcode::Trapif`
* [ ] `Opcode::Trapff`
* [ ] `Opcode::FuncAddr`
* [ ] `Opcode::SymbolValue`
* [ ] `Opcode::Call`
* [ ] `Opcode::CallIndirect`
* [ ] `Opcode::GetPinnedReg`
* [ ] `Opcode::SetPinnedReg`
* [ ] `Opcode::Vconst`
* [ ] `Opcode::RawBitcast`
* [ ] `Opcode::Extractlane`
* [ ] `Opcode::Insertlane`
* [ ] `Opcode::Splat`
* [ ] `Opcode::ScalarToVector`
* [ ] `Opcode::VallTrue`
* [ ] `Opcode::VanyTrue`
* [ ] `Opcode::VhighBits`
* [ ] `Opcode::Shuffle`
* [ ] `Opcode::Swizzle`
* [ ] `Opcode::Isplit`
* [ ] `Opcode::Iconcat`
* [ ] `Opcode::Imax`
* [ ] `Opcode::Umax`
* [ ] `Opcode::Umin`
* [ ] `Opcode::Imin`
* [ ] `Opcode::IaddPairwise`
* [ ] `Opcode::WideningPairwiseDotProductS`
* [ ] `Opcode::Fadd`
* [ ] `Opcode::Fsub`
* [ ] `Opcode::Fmul`
* [ ] `Opcode::Fdiv`
* [ ] `Opcode::Fmin`
* [ ] `Opcode::Fmax`
* [ ] `Opcode::FminPseudo`
* [ ] `Opcode::FmaxPseudo`
* [ ] `Opcode::Sqrt`
* [ ] `Opcode::Fneg`
* [ ] `Opcode::Fabs`
* [ ] `Opcode::Fpromote`
* [ ] `Opcode::Fdemote`
* [ ] `Opcode::Ceil`
* [ ] `Opcode::Floor`
* [ ] `Opcode::Trunc`
* [ ] `Opcode::Nearest`
* [ ] `Opcode::Fma`
* [ ] `Opcode::Fcopysign`
* [ ] `Opcode::FcvtToUint`
* [ ] `Opcode::FcvtToSint`
* [ ] `Opcode::FcvtFromUint`
* [ ] `Opcode::FcvtFromSint`
* [ ] `Opcode::FcvtToUintSat`
* [ ] `Opcode::FcvtToSintSat`
* [ ] `Opcode::IaddIfcout`
* [ ] `Opcode::Iabs`
* [ ] `Opcode::AvgRound`
* [ ] `Opcode::Snarrow`
* [ ] `Opcode::Unarrow`
* [ ] `Opcode::Uunarrow`
* [ ] `Opcode::SwidenLow`
* [ ] `Opcode::SwidenHigh`
* [ ] `Opcode::UwidenLow`
* [ ] `Opcode::UwidenHigh`
* [ ] `Opcode::TlsValue`
* [ ] `Opcode::SqmulRoundSato`
* [ ] `Opcode::FcvtLowFromSint`
* [ ] `Opcode::FvpromoteLow`
* [ ] `Opcode::Fvdemote`

</details>

# s390x

<details>

* [ ] Calls
* [ ] Returns
* [ ] Traps
* [ ] Branches

</details>

**Comment by sparker-arm** [comment]
I'm picking up AtomicRMW for AArch64.

**Comment by cfallin** [comment]
I'm going to start working down the `x86_64` opcode list from the top -- clz/btz/popcnt/bitrev to start, I think. @abrown let me know what your next plans are and we can make sure not to duplicate work!

**Comment by abrown** [comment]
Just for the record, I am working on x64's `icmp`, `fcmp` and `select` instructions.

**Comment by jlb6740** [comment]
Thanks @abrown. @abrown @cfallin for the record, I'd like to get started with something simple. I'd like to claim fabs and fneg.

**Comment by abrown** [comment]
I'm looking at loads and stores next, FYI.

**Comment by sparker-arm** [comment]
I'm picking up AtomicCas and IaddPairwise for aarch64.

**Comment by cfallin** [comment]
@abrown are you still planning to take a look at stores on x64? I'm happy to take those first thing Mon if you haven't started yet, as I've got some isel improvements I want to do that involve them (load-op-store patterns). If you're close then no worries though!

**Comment by abrown** [comment]
Well, I haven't started stores yet... so take them if you want to!

**Comment by sparker-arm** [comment]
I've also picked up snarrow, unarrow, uunarrow and fvdemote.

**Comment by elliottt** [comment]
I've finished up translating icmp for x64

**Comment by afonso360** [comment]
Last week we also merged `bmask`/`bextend`/`ireduce`/`breduce` for aarch64

**Comment by dheaton-arm** [comment]
I've picked up `iabs` for aarch64.

**Comment by dheaton-arm** [comment]
And also picked up `swizzle` and `scalartovector`.

**Comment by elliottt** [comment]
I'm working on finishing the x64 migration to ISLE. Feel free to grab instructions if you'd like to work on them, otherwise I'll continue working down the list.

**Comment by cfallin** [comment]
@dheaton-arm I'm planning to help push the aarch64 work to completion; I'm hoping to tackle some of the trickier remaining ones (loads and stores, with amode lowering; calls; branches; icmp/fcmp and flags users). Is that OK or have you already started on some of these?

**Comment by dheaton-arm** [comment]
I've already started on icmp and fcmp, but everything you've mentioned before those should be fine.

**Comment by akirilov-arm** [comment]
@cfallin I have an upcoming patch that moves the `AMode` enum definition to ISLE, but I don't plan to touch the actual lowering rules for loads and stores. We already have the `amode` helper in ISLE, so the latter bit should be doable without waiting for my patch to land (of course, `AMode` lowering itself would depend on it).

My patch changes quite a lot of code because, as far as I can tell, enum definitions in ISLE always result in enums with named fields, while the existing `AMode` enum has unnamed fields.

**Comment by cfallin** [comment]
OK great, I'll take loads/stores themselves, calls, and branches. Lowering of flags-using instructions will intersect with how we do icmp/fcmp so I'll hold off on those. Thanks!

> My patch changes quite a lot of code because, as far as I can tell, enum definitions in ISLE always result in enums with named fields, while the existing AMode enum has unnamed fields.

Yep, but there's no fundamental reason for that, it was just a "build it as we need it" sort of thing. We could look at supporting unnamed-field enum variants if it's simpler; it would probably be a 1-2 day refactor.

**Comment by cfallin** [comment]
Put up PRs for call/ret and loads/stores today; the remaining instructions on aarch64 that don't depend on flags or pattern-matching with icmp/fcmp somehow are:

- GetPinnedReg/SetPinnedReg
- ExtractLane/InsertLane
- StackAddr
- IaddIfcout
- TlsValue

I'm happy to do all of these tomorrow, unless someone else objects or has partial work here, then I can do the branch and flags-related ones (trueif/trueff, selectif/selectff/select, brif/brff/brz/brnz) once @dheaton-arm 's icmp/fcmp work is done.

**Comment by elliottt** [comment]
The x86_64 backend has been migrated to ISLE :tada:

**Comment by dheaton-arm** [comment]
> I'm happy to do all of these tomorrow, unless someone else objects or has partial work here, then I can do the branch and flags-related ones (trueif/trueff, selectif/selectff/select, brif/brff/brz/brnz) once @dheaton-arm 's icmp/fcmp work is done.

@cfallin Just as a heads up, after my `icmp` patch I've been working on `true{if,ff}` and `select{_,if,ff}`. I haven't started on the `br*` ops though. :)

**Comment by cfallin** [comment]
@dheaton-arm great! I shifted over to some regalloc semantics cleanup work but I can come back and do `br*` ops next, likely Thu or Fri, unless you want to claim then before then!

**Comment by dheaton-arm** [comment]
> @dheaton-arm great! I shifted over to some regalloc semantics cleanup work but I can come back and do `br*` ops next, likely Thu or Fri, unless you want to claim then before then!

I'm starting on the branch ops now, assuming you haven't yet. (Starting with `jump` and `br_icmp`..`brff`.)

**Comment by dheaton-arm** [comment]
The AArch64 backend has now been fully ported to ISLE.

**Comment by fitzgen** [comment]
Unless I'm missing something, that means we can close this issue! Thanks so much to everyone who helped make this migration happen!

**Comment by cfallin** [comment]
Thanks so much @dheaton-arm and other Arm folks (@akirilov-arm, @sparker-arm) for your contributions to this effort! It is great that we finally have everything in the DSL; this is going to enable us to make a bunch more improvements in the future, and really does help a lot.
