### ISSUE TITLE
Tracking issue for shared memory

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#4245]
This issue tracks anything incomplete with the effort to add shared memories started in #4187:

 - [x] https://github.com/bytecodealliance/wasm-tools/pull/624
 - [x] https://github.com/bytecodealliance/wasmtime/pull/4266
 - [x]  improve tests (@alexcrichton had a [comment](https://github.com/bytecodealliance/wasmtime/pull/4187#discussion_r891697133) about trying to stress things by doing more in Wasm)
 - [ ] add a `SharedMemoryType` to the `wasmtime` external API (@alexcrichton wanted this to disambiguate entirely between memories and shared memories
 - [x] enable shared memory in the C API (#7940)
 - [ ] #4244
 - [ ] #4240
 - [ ] #4203
 - [x] #4267 
 - [ ] #4268
 - [ ] Growth/creation of a shared memory is not subject to resource limiters 
 - [ ] Shared memories are disabled by default in Wasmtime
 - [ ] Pulley's reconcilation with shared memories may or may not have holes (unsure)
 - [ ] Behavior of wait/notify aren't customizable #12809
