### ISSUE TITLE
cranelift: Tracking issue for Interpreter support

### ISSUE THREAD

**Issue by afonso360** [bytecodealliance/wasmtime#4889]
Hey,

I did a roundup of what is supported in the interpreter and what is tested or not. Now that we have multiple people working on the interpreter this is probably a better way to keep track of what is going on an who is working on what.

### Labels:
✔ - Implemented and tested for all types
🟡 - Implemented for some types / Missing some tests
❌ - Unimplemented

### Opcodes
- [x] `Opcode::Jump` - ✔
- [ ] `Opcode::Brz` - 🟡
    - [ ] I128 tests disabled
- [ ] `Opcode::Brnz` - 🟡
    - [ ] I128 tests disabled
- [ ] `Opcode::BrIcmp` - 🟡
    - [ ] I128 tests disabled
- [x] `Opcode::BrTable` - ✔
- [ ] `Opcode::Trap` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Debugtrap` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::ResumableTrap` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Trapz` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Trapnz` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::ResumableTrapnz` - 🟡
    - [ ] Missing tests
- [x] `Opcode::Return` - ✔
- [x] `Opcode::Call` - ✔
- [ ] `Opcode::CallIndirect` - ❌
- [ ] `Opcode::FuncAddr` - ❌
- [x] `Opcode::Load` - ✔
- [ ] `Opcode::Uload8` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Sload8` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Uload16` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Sload16` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Uload32` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Sload32` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Uload8x8` - ❌
- [ ] `Opcode::Sload8x8` - ❌
- [ ] `Opcode::Uload16x4` - ❌
- [ ] `Opcode::Sload16x4` - ❌
- [ ] `Opcode::Uload32x2` - ❌
- [ ] `Opcode::Sload32x2` - ❌
- [x] `Opcode::Store` - ✔
- [ ] `Opcode::Istore8` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Istore16` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Istore32` - 🟡
    - [ ] Missing tests
- [x] `Opcode::StackLoad` - ✔
- [x] `Opcode::StackStore` - ✔
- [x] `Opcode::StackAddr` - ✔
- [ ] `Opcode::DynamicStackAddr` - ❌
- [ ] `Opcode::DynamicStackLoad` - ❌
- [ ] `Opcode::DynamicStackStore` - ❌
- [x] `Opcode::GlobalValue` - ✔
- [ ] `Opcode::SymbolValue` - ❌
- [ ] `Opcode::TlsValue` - ❌
- [x] `Opcode::HeapAddr` - ✔
- [x] `Opcode::GetPinnedReg` - ✔
- [x] `Opcode::SetPinnedReg` - ✔
- [x] `Opcode::TableAddr` - ✔
- [x] `Opcode::Iconst` - ✔
- [x] `Opcode::F32const` - ✔
- [x] `Opcode::F64const` - ✔
- [x] `Opcode::Bconst` - ✔
- [x] `Opcode::Vconst` - ✔
- [ ] `Opcode::Null` - ❌
- [ ] `Opcode::Nop` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Select` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Bitselect` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Copy` - 🟡
    - [ ] Missing tests
- [x] `Opcode::Icmp` - ✔
- [ ] `Opcode::Imin` - 🟡
    - [ ] Missing i128 tests
    - [ ] Missing some SIMD tests (i64x2)
- [ ] `Opcode::Umin` - 🟡
    - [ ] Missing i128 tests
    - [ ] Missing some SIMD tests (i64x2)
- [ ] `Opcode::Imax` - 🟡
    - [ ] Missing i128 tests
    - [ ] Missing some SIMD tests (i64x2)
- [ ] `Opcode::Umax` - 🟡
    - [ ] Missing i128 tests
    - [ ] Missing some SIMD tests (i64x2)
- [ ] `Opcode::AvgRound` - 🟡
    - [ ] Implemented for scalar, but not tested
    - [ ] SIMD tests disabled
- [x] `Opcode::Iadd` - ✔
- [x] `Opcode::UaddSat` - ✔
- [x] `Opcode::SaddSat` - ✔
- [x] `Opcode::Isub` - ✔
- [x] `Opcode::UsubSat` - ✔
- [x] `Opcode::SsubSat` - ✔
- [ ] `Opcode::Ineg` - 🟡
    - [ ] Only tested for i32x4
- [ ] `Opcode::Iabs` - 🟡
    - [ ] Missing i128 tests
- [x] `Opcode::Imul` - ✔
- [x] `Opcode::Umulhi` - ✔
- [x] `Opcode::Smulhi` - ✔
- [x] `Opcode::Udiv` - ✔
- [x] `Opcode::Sdiv` - ✔
- [x] `Opcode::Urem` - ✔
- [x] `Opcode::Srem` - ✔
- [ ] `Opcode::IaddCin` - 🟡
    - [ ] Missing I128 tests
- [ ] `Opcode::IaddCout` - 🟡
    - [ ] Missing I128 tests
- [ ] `Opcode::IaddCarry` - 🟡
    - [ ] Missing I128 tests
- [ ] `Opcode::IsubBin` - 🟡
    - [ ] Missing I128 tests
- [ ] `Opcode::IsubBout` - 🟡
    - [ ] Missing I128 tests
- [ ] `Opcode::IsubBorrow` - 🟡
    - [ ] Missing I128 tests
- [ ] `Opcode::Band` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Bor` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Bxor` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Bnot` - 🟡
    - [ ] Tests are disabled
- [ ] `Opcode::BandNot` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::BorNot` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::BxorNot` - 🟡
    - [ ] Missing tests
- [x] `Opcode::Rotl` - ✔
    - [ ] SIMD tests missing
- [x] `Opcode::Rotr` - ✔
    - [ ] SIMD tests missing
- [x] `Opcode::Ishl` - ✔
    - [ ] SIMD tests disabled
- [x] `Opcode::Ushr` - ✔
    - [ ] SIMD tests disabled
- [ ] `Opcode::Sshr` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Bitrev` - 🟡
    - [ ] I128 tests disabled
- [ ] `Opcode::Clz` - 🟡
    - [ ] I128 tests disabled
- [ ] `Opcode::Cls` - 🟡
    - [ ] I128 tests disabled
- [ ] `Opcode::Ctz` - 🟡
    - [ ] I128 tests disabled
- [ ] `Opcode::Popcnt` - 🟡
    - [ ] I128 tests disabled
- [ ] `Opcode::Fcmp` - 🟡
    - [ ] Missing SIMD tests
- [ ] `Opcode::Fadd` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Fsub` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Fmul` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Fdiv` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Sqrt` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Fma` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Fneg` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Fabs` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Fcopysign` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Fmin` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::FminPseudo` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Fmax` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::FmaxPseudo` - 🟡
    - [ ] SIMD tests disabled
- [ ] `Opcode::Ceil` - 🟡
    - [ ] Missing SIMD tests
- [ ] `Opcode::Floor` - 🟡
    - [ ] Missing SIMD tests
- [ ] `Opcode::Trunc` - 🟡
    - [ ] Missing SIMD tests
- [ ] `Opcode::Nearest` - 🟡
    - [ ] Missing SIMD tests
- [ ] `Opcode::IsNull` - ❌
- [ ] `Opcode::IsInvalid` - ❌
- [ ] `Opcode::Bitcast` - 🟡
    - [ ] Missing tests for all types
- [ ] `Opcode::RawBitcast` - 🟡
    - [ ] Missing tests for scalar types
- [ ] `Opcode::ScalarToVector` - 🟡
    - [ ] Tests disabled
- [x] `Opcode::Breduce` - ✔
- [x] `Opcode::Bextend` - ✔
- [x] `Opcode::Ireduce` - ✔
- [ ] `Opcode::Bint` - 🟡
    - [ ] Missing SIMD tests
- [x] `Opcode::Snarrow` - ✔
- [x] `Opcode::Unarrow` - ✔
- [x] `Opcode::Uunarrow` - ✔
- [x] `Opcode::Bmask` - ✔
- [x] `Opcode::Sextend` - ✔
- [x] `Opcode::Uextend` - ✔
- [ ] `Opcode::Fpromote` - 🟡
    - [ ] Tests disabled
- [ ] `Opcode::Fdemote` - 🟡
    - [ ] Tests disabled
- [x] `Opcode::Shuffle` - ✔
- [ ] `Opcode::Swizzle` - 🟡
    - [ ] Only tested for i8x16
- [ ] `Opcode::Splat` - 🟡
    - [ ] Tests disabled
- [ ] `Opcode::Insertlane` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Extractlane` - 🟡
    - [ ] Missing tests
- [x] `Opcode::VhighBits` - ✔
- [ ] `Opcode::Vsplit` - ❌
- [ ] `Opcode::Vconcat` - ❌
- [x] `Opcode::Vselect` - ✔
- [x] `Opcode::VanyTrue` - ✔
- [x] `Opcode::VallTrue` - ✔
- [x] `Opcode::SwidenLow` - ✔
- [x] `Opcode::SwidenHigh` - ✔
- [x] `Opcode::UwidenLow` - ✔
- [x] `Opcode::UwidenHigh` - ✔
- [ ] `Opcode::FcvtToUint` - ❌
- [ ] `Opcode::FcvtToUintSat` - ❌
- [ ] `Opcode::FcvtToSint` - ❌
- [ ] `Opcode::FcvtToSintSat` - ❌
- [ ] `Opcode::FcvtFromUint` - ❌
- [ ] `Opcode::FcvtFromSint` - ❌
- [ ] `Opcode::FcvtLowFromSint` - ❌
- [ ] `Opcode::FvpromoteLow` - ❌
- [ ] `Opcode::Fvdemote` - ❌
- [x] `Opcode::Isplit` - ✔
- [x] `Opcode::Iconcat` - ✔
- [ ] `Opcode::AtomicRmw` - ❌
- [ ] `Opcode::AtomicCas` - ❌
- [ ] `Opcode::AtomicLoad` - ❌
- [ ] `Opcode::AtomicStore` - ❌
- [ ] `Opcode::Fence` - ❌
- [x] `Opcode::WideningPairwiseDotProductS` - ✔
- [ ] `Opcode::SqmulRoundSat` - 🟡
    - [ ] Missing tests for types other than i16x8
- [x] `Opcode::IaddPairwise` - ✔
- [ ] `Opcode::ExtractVector` - ❌
- [ ] `Opcode::GetFramePointer` - ❌
- [ ] `Opcode::GetStackPointer` - ❌
- [ ] `Opcode::GetReturnAddress` - ❌

### Op+Imm

These may be going away, see: #4721

- [ ] `Opcode::IaddImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::ImulImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::UdivImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::SdivImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::UremImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::SremImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::IrsubImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::BandImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::BorImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::BxorImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::RotlImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::RotrImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::IshlImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::UshrImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::SshrImm` - 🟡
    - [ ] Missing tests for some types
- [ ] `Opcode::IcmpImm` - 🟡
    - [ ] Missing tests for some types

### Flag Ops

These may be going away, see: #3249

- [ ] `Opcode::Brif` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Brff` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Trueif` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Trueff` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::IsubIfbout` - ❌
- [ ] `Opcode::IaddIfcin` - ❌
- [ ] `Opcode::IaddIfcout` - ❌
- [ ] `Opcode::IaddIfcarry` - ❌
- [ ] `Opcode::IsubIfbin` - ❌
- [ ] `Opcode::IsubIfborrow` - ❌
- [ ] `Opcode::Ffcmp` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Ifcmp` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::IfcmpImm` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Trapif` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Trapff` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::Selectif` - 🟡
    - [ ] Missing tests
- [ ] `Opcode::SelectifSpectreGuard` - ❌
