### ISSUE TITLE
Tracking issue for MPK

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmtime#7119]
This issue tracks anything incomplete with the effort to add shared memories started in #7072:

- [ ] fix tests when MPK is enabled (e.g., some tests of instance limits change due to striping)
- [ ] add WebAssembly-level tests checking that MPK-protected slots cannot access OOB regions
- [ ] handle protection key changes across asynchronous `block_on` changes (see `store.rs:1947`)
- [ ] figure out a way to run with MPK enabled in CI (QEMU?)
- [ ] enable MPK in fuzz targets
- [ ] fix up the MPK and `memory_pool` documentation; e.g., remove duplication
- [ ] benchmark `call` performance with PKRU switch
