### ISSUE TITLE
Tracking issue for supporting multithreaded WebAssembly

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#888]
I've noticed that there's a few issues related to threads lying around, so I figure it's a good idea to go ahead and open a dedicated tracking issue for various work items. The work here that needs to happen I believe is:

* [ ] Cranelift needs atomics support - bytecodealliance/cranelift#582
* [ ] Ensure `wasmtime` internal data structures are threadsafe
  * `wasmtime_runtime::LinearMemory`
  * `wasmtime::{Store, Module, Memory}` (see https://github.com/bytecodealliance/wasmtime/issues/777)
  * ...
* [ ] Design a WASI (or other) API to spawn a thread
* [ ] Port an existing library to this infrastructure and prove it out.

**Comment by bjorn3** [comment]
> Port an existing library to this infrastructure and prove it out.

For atomics using cg_clif to compile a heavy atomics user like veloren (through rayon) should prove it. This would not need wasmtime to be made completely threadsafe, so it can likely be faster, as it is just changing the codegen for a few intrinsics in cg_clif.

**Comment by rene-fonseca** [comment]
I'll gladly help with the testing as the features are added for my project.

Also note that we need implementations of the C++ ABI like __cxa_guard_acquire/__cxa_guard_release or we would get into race conditions with static vars.

**Comment by bjorn3** [comment]
I think that is only necessary for C++ local static vars. According to https://arkaitzj.wordpress.com/tag/__cxa_guard_acquire/ their constructor is only called on the first use. For this to be thread safe, __cxa_guard_acquire and __cxa_guard_release are necessary. WASM however doesn't have lazily initialized globals. Also WASM globals can only store primitive types, so atomic instructions are enough.

**Comment by sunfishcode** [comment]
Wasm does support C++ global/static variables with arbitrary types; they are allocated in wasm's linear memory rather than in global variables at the wasm level. It has lazy inits, with guard variables, following the Itanium C++ ABI. Fortunately, `__cxa_guard_acquire` and `__cxa_guard_release` are defined as library functions in [`libcxxabi`](https://github.com/llvm/llvm-project/blob/master/libcxxabi/src/cxa_guard_impl.h), so we don't need any new host APIs for them.

**Comment by sparker-arm** [comment]
Hi @alexcrichton, is this still the current TODO list for threading support? This there a more detailed roadmap to look at?

**Comment by bjorn3** [comment]
Cranelift has support for atomics, so that checkbox should be checked.

**Comment by alexcrichton** [comment]
AFAIK it's basically still relevant, yeah. I don't believe that much work has been done to implement this in Wasmtime. I believe that most atomic operations are supported in Cranelift now as-mentioned but that's just the tip of the iceberg. I'm not sure how thoroughly tested they are or whether there's some missing instructions needing an implementation. I also don't know if normal loads/stores with memory need to be updated and/or change codegen in a shared-memory world. Overall I don't think we're in the position where we can simply say Cranelift is "done" and the work is elsewhere, but I could be wrong!

There's still quite a lot to do with Wasmtime itself. Designing shared memories and how that will work has not yet been done.

**Comment by muayyad-alsadi** [comment]
I have a question when we say threading support do we mean the ability to

* to start a thread from a wasm function
* to be safely called from two different threads (that are started outside wasm ex. by the WASI env, eg. python)

I'm more interested in the second

**Comment by abrown** [comment]
@muayyad-alsadi, for the "spawning a thread" question, you might be interested in wasi-threads, which you could read about in this [blog post](https://bytecodealliance.org/articles/wasi-threads). For the second question, I think @bjorn3 is right; I would just add that care has been taken to ensure that the API is thread-safe, mainly by using Rust's thread-safety restrictions. E.g., if you try to do something unsafe using Wasmtime's API, the Rust compiler should complain.

@alexcrichton, I think we can close this issue?

**Comment by alexcrichton** [comment]
Agreed!
