### ISSUE TITLE
Tracking issue for the bulk memory operations proposal

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#928]
This is a tracking issue for [the bulk memory operations proposal](https://github.com/WebAssembly/bulk-memory-operations).

### TODO:

* [x] Enable the bulk memory proposal's test suite
    * [x] `binary.wast`
    * [x] `bulk.wast`
    * [x] `custom.wast`
    * [x] `data.wast`
    * [x] `elem.wast`
    * [x] `imports.wast`
    * [x] `linking.wast`
    * [x] `memory_copy.wast`
    * [x] `memory_fill.wast`
    * [x] `memory_init.wast`
    * [x] `table_init.wast`
    * [x] `table_copy.wast`
* [x] Enable bulk memory in the fuzzers

**Comment by fitzgen** [comment]
Done!
