### ISSUE TITLE
Tracking issue for the reference types proposal

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#929]
This is a tracking issue for [the reference types proposal](https://github.com/WebAssembly/reference-types).

### TODO

* [x] Depends on bulk memory: #928
* [x] Enable the reference types proposal's test suite
    * [x] `binary.wast`
    * [x] `br_table.wast`
    * [x] `exports.wast`
    * [x] `globals.wast`
    * [x] `imports.wast`
    * [x] `linking.wast`
    * [x] `memory_grow.wast`
    * [x] `ref_func.wast`
    * [x] `ref_is_null.wast`
    * [x] `ref_null.wast`
    * [x] `select.wast`
    * [x] `table_fill.wast`
    * [x] `table_get.wast`
    * [x] `table_grow.wast`
    * [x] `table_set.wast`
    * [x] `table_size.wast`
    * [x] `unreached_invalid.wast`
* [x] Enable reference types in the fuzzers
* [x] Do not leak `externref`s passed into Wasm: https://github.com/bytecodealliance/wasmtime/issues/1804
* [x] Enable `Func::wrap` support for functions using reference types: https://github.com/bytecodealliance/wasmtime/issues/1868
* [ ] Support reference types on aarch64: https://github.com/bytecodealliance/wasmtime/issues/1886
* [ ] Enable reference types by default

#### Support Reference Types in Language Embedding APIs

* [x] Ensure that the Rust API supports reference types and new reference types operations
* [x] Expose reference types in the C API
* [x] Support reference types in the Go API
* [x] Support reference types in the .NET API
* [x] Support reference types in the Python API

**Comment by fitzgen** [comment]
fyi, enough to get an `externref -> externref` identity function working just landed in https://github.com/bytecodealliance/wasmtime/pull/1781

**Comment by fitzgen** [comment]
All spec tests are now passing on `main`.

**Comment by alexcrichton** [comment]
Reference types have been implemented and enabled for some time now, so closing.
