### ISSUE TITLE
List of future optimizations for Wasm GC performance

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/wasmtime#9351]
* [ ] Speed up getting and setting `funcref`s inside GC objects: https://github.com/bytecodealliance/wasmtime/issues/9347
* [ ] Const fold through `uadd_overflow_trap`/`trap{z,nz}` insts that show up frequently in GC heap accesses: https://github.com/bytecodealliance/wasmtime/issues/5908
* [ ] Type-based alias analysis for Wasm GC: https://github.com/bytecodealliance/wasmtime/issues/9348
* [ ] Escape analysis for Wasm GC: https://github.com/bytecodealliance/wasmtime/issues/9349
* [ ] Reuse linear memories and their optimized bounds checks for Wasm GC heaps: https://github.com/bytecodealliance/wasmtime/issues/9350

**Comment by fitzgen** [comment]
See also https://github.com/WebAssembly/gc/issues/565 for potential benchmarks.

**Comment by fitzgen** [comment]
Closing this meta issue since all work is already captured in sub-issues and they're all labeled appropriately.
