### ISSUE TITLE
Pulley TODO List

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime#9747]
I'd like a place to throw small items as I see them and to collect various TODO items during the development of Pulley. For now this will serve that location. My hope is that this list is TODO items which pertain to code in-tree and are less-so about wishlist items of what's yet to fill in. For example this won't track missing pulley work (e.g. all wasm proposals at this time). Unsure if this style of issue will work out.

- [ ] Evaluate 32-bit platforms and the decision to "only write low 32-bits". If we write the full 64-bit width of registers does it actually have a performance loss? Is it worth burning opcode space for opcodes that only write the low-32 instead of high 64? Should we split opcodes like `xconst8` into one that writes 64-bits and one that writes 32-bits? Should we remove `xload8_s32_offset32` instead?
- [x] Add support for Pulley to `#[wasmtime_test]` https://github.com/bytecodealliance/wasmtime/pull/10057
- [x] Move sp/fp/lr/special regs out of the general purpose register set; see https://github.com/bytecodealliance/wasmtime/pull/9658#pullrequestreview-2482824188 for details (also cc https://github.com/bytecodealliance/wasmtime/pull/9806)
- [x] Explore adding new addressing modes (e.g. register + register). Should be based on an evaluation of what wasm loads/stores do probably. Perhaps even fold a trapping arithmetic into one macro-op for "do the wasm load on 32-bit" and "do the wasm load on 64-bit" https://github.com/bytecodealliance/wasmtime/pull/9994
- [x] Assert in call lowering that pulley<->pulley is always tail-to-tail or similar; see https://github.com/bytecodealliance/wasmtime/pull/9665#discussion_r1871969050 for details -- https://github.com/bytecodealliance/wasmtime/pull/9836
- [x] Better debugging support, e.g. print the register state between instructions and print each instruction. https://github.com/bytecodealliance/wasmtime/pull/9796
- [x] Support big-endian - will need to add `pulley{64,32}be` targets to target-lexicon, then add big-endian loads/stores, then update the CLIF backend to delegate to the right endianness based on the target
- [x] Need to restore callee-save state when a trap happens somehow (either via explicit saves or by removing callee-save state in that situation) https://github.com/bytecodealliance/wasmtime/pull/9837
- [x] Enable Cranelift `runtest` support https://github.com/bytecodealliance/wasmtime/pull/9795
- [X] Run the full `all` test suite on 32-bit platforms -- https://github.com/bytecodealliance/wasmtime/pull/9837
- [x] Figure out story for threading -- loads/stores all need to be at least with a "relaxed" atomicity -- https://github.com/bytecodealliance/wasmtime/pull/9818
- [x] Implement the wide-arithmetic proposal https://github.com/bytecodealliance/wasmtime/pull/9944
- [x] Fuzz pulley https://github.com/bytecodealliance/wasmtime/pull/9966

**Comment by alexcrichton** [comment]
Notes for big-endian:

* Need to add big-endian targets for Cranelift --  https://github.com/bytecodealliance/target-lexicon/pull/115
* Pulley loads/stores will all have annotated endianness, nothing is "native endian"
* New big-endian loads/stores to get added under the "extended" opcode space
* Cranelift will use its configuration to select the appropriate pulley instruction, e.g. "native endianness" is whatever the configured target uses

**Comment by alexcrichton** [comment]
I think that this issue has served it's purpose and is largely done, so I'm going to close this.
